#!/bin/bash
mkdir -p ${FLOAT34INTERVALPATH}

./Log ${FLOAT34INTERVALPATH}/Float34ROLogIntervals ${ORACLEPATH}/Float34ROLogOracle
./Log2 ${FLOAT34INTERVALPATH}/Float34ROLog2Intervals ${ORACLEPATH}/Float34ROLog2Oracle
./Log10 ${FLOAT34INTERVALPATH}/Float34ROLog10Intervals ${ORACLEPATH}/Float34ROLog10Oracle
./Exp ${FLOAT34INTERVALPATH}/Float34ROExpIntervals ${ORACLEPATH}/Float34ROExpOracle
./Exp2 ${FLOAT34INTERVALPATH}/Float34ROExp2Intervals ${ORACLEPATH}/Float34ROExp2Oracle
./Exp10 ${FLOAT34INTERVALPATH}/Float34ROExp10Intervals ${ORACLEPATH}/Float34ROExp10Oracle
./Sinh ${FLOAT34INTERVALPATH}/Float34ROSinhForSinhIntervals ${FLOAT34INTERVALPATH}/Float34ROCoshForSinhIntervals ${ORACLEPATH}/Float34ROSinhOracle
./Cosh ${FLOAT34INTERVALPATH}/Float34ROSinhForCoshIntervals ${FLOAT34INTERVALPATH}/Float34ROCoshForCoshIntervals ${ORACLEPATH}/Float34ROCoshOracle
./Sinpi ${FLOAT34INTERVALPATH}/Float34ROSinpiForSinpiIntervals ${FLOAT34INTERVALPATH}/Float34ROCospiForSinpiIntervals ${ORACLEPATH}/Float34ROSinpiOracle
./Cospi ${FLOAT34INTERVALPATH}/Float34ROSinpiForCospiIntervals ${FLOAT34INTERVALPATH}/Float34ROCospiForCospiIntervals ${ORACLEPATH}/Float34ROCospiOracle
